### PR TITLE
Improve UI/UX

### PR DESCRIPTION
**Pull request by Djdany95**
Can you check if this corrects #20 and #16 ?

Thanks!

### CODE REVIEW

**Comment by niamurrell** [comment]
Thanks @djdany01 for this! Can you split the home button off to a different PR from the Today Use? I am happy to merge the home button now but had already done a bit of work on the today button functionality, so will need to see what overlaps before merging.

**Comment by Djdany95** [comment]
Yes ofc! 😄

**Comment by Djdany95** [comment]
Done, you can check the other PR #23

**Comment by niamurrell** [comment]
Stale

**Pull request closed without merging**
