### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Ananthavijay**
### What was a problem? (include issue # if applicable)

{nothing} https://github.com/niamurrell/value-app/issues/14

### How does this PR fix the problem?

{This PR updates the contribution guidelines}

### Check lists (check `x` in `[ ]` of list items)

- [X] Changes were already discussed in issues (optional but please note here either way)
- [X] Meaningful commit messages
- [X] Code runs without any issues

### Additional Comments (if any)

{nothing} 
@niamurrell I think you could make an issue to update PR template. I would like to work on it as well

### CODE REVIEW

**Comment by niamurrell** [comment]
Thanks @Ananthavijay! Looks great. Could you revise your addition to note squashing as an _optional_ last step? I'm trying to keep the repo as beginner-friendly as possible for Hacktoberfest, and personally don't really mind several commits as long as they're meaningful.  

For the PR template I agree, this one can use some improvement—feel free to open an issue and work on that 👍

**Comment by Ananthavijay** [comment]
Then I guess squashing commits should be removed

**Comment by niamurrell** [comment]
Sure, maybe remove step 7 but it's good to keep in the list of links in case people want to learn about it. It is useful.

Or you could just note that step 7 is optional.

**Comment by Ananthavijay** [comment]
Done @niamurrell

**Comment by Ananthavijay** [comment]
Without knowing closed it

**Comment by Ananthavijay** [comment]
pls review @niamurrell

**Pull request merged**
